### ISSUE TITLE
Implement number of records count for an index

### ISSUE THREAD

**Issue by l4u** [algolia/algoliasearch-client-ruby#15]
My first try was to use `index.browse['nbHits']`. But it gets 1000 records.
Currently, I am using `index.search('', { hitsPerPage: 0 })['nbHits']`.

It would be nice to add a method `index.number_of_records` or `index.records_count` in this gem.

**Comment by dethi** [comment]
Hello,
It should work with `browse`, without the need to retrieve any records:

```ruby
index.browse(hitsPerPage=0)['nbHits']
```

**Comment by dethi** [comment]
Also, you can't use `search` for this use case because `search` can only retrieve the first 1.000 hits for performance and security reasons. :)

**Comment by l4u** [comment]
Both `browse` and `search` gave me the same count.
Anyway I will use your recommended approach.
Thanks!

**Comment by l4u** [comment]
`index.browse(hitsPerPage=0)['nbHits']` will try to fetch 1000 records.
it should be `index.browse(nil, 0)['nbHits']`

**Comment by dethi** [comment]
Oh yes sorry. It works with `search` too!

**Comment by redox** [comment]
@l4u You should keep in mind that if you use pass any query string or parameters, the `nbHits` value will be approximated as soon as you have a lot of results (for performance reason). For the empty query and no filters, it's OK!

I'm closing this issue because we probably don't want to expose more in our API clients.
