### ISSUE TITLE
browse documentation doesn't make any sense

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-client-ruby#33]
Docs around 

```ruby
# Iterate with a filter over the index
index.browse({:query => "test", :numericFilters => 'i=42'}) do
    # Do something
end
```

need work - the block is passed something weird and is not explained

**Comment by vincentwoo** [comment]
here's some terrifying shit:

```
42] pry(main)> index.browse.each { |hash| puts hash.class }; 2
Array
Array
Array
Array
Array
Array
Array
Array
Array
2
[43] pry(main)> index.browse.each { |arr, str| puts arr.class }; 2
String
String
String
String
String
String
String
String
String
2
[44] pry(main)> index.browse.each { |arr| puts arr.class }; 2
Array
Array
Array
Array
Array
Array
Array
Array
Array
2
[45] pry(main)> index.browse.each { |arr| puts arr[0] }; 2
hits
nbHits
page
nbPages
hitsPerPage
processingTimeMS
query
params
cursor
2
```

**Comment by redox** [comment]
Yes, probably a lack of documentation here. Here is what the code is doing:

```ruby
            if block.arity == 2
              yield hit, @cursor
            else
              yield hit
            end
```

So you should do:

```ruby
index.browse({:query => "test", :numericFilters => 'i=42'}) do |hit|
    # Do something
end
```

or

```ruby
index.browse({:query => "test", :numericFilters => 'i=42'}) do |hit, cursor|
    # Do something
end
```

**Comment by vincentwoo** [comment]
Come on, I'm not dumb. Your code is straight up broken and you probably need to rewrite your `browse` impl:

```
[5] pry(main)> index.browse({:query => "test"}) do |hit|
[5] pry(main)*   puts hit.class
[5] pry(main)* end
[algoliasearch-rails] Cannot GET to https://VXINIRAKQB-dsn.algolia.net/1/indexes/Question_development/browse?page=%7B%3Aquery%3D%3E%22test%22%7D&hitsPerPage=1000: {"message":"Invalid value for page parameter","status":400}

 (400)
[algoliasearch-rails] Cannot GET to https://VXINIRAKQB-dsn.algolia.net/1/indexes/Question_development/browse?page=%7B%3Aquery%3D%3E%22test%22%7D&hitsPerPage=1000: {"message":"Invalid value for page parameter","status":400}

 (400)
{
    "error" => #<Algolia::AlgoliaProtocolError: 400: Cannot GET to https://VXINIRAKQB-dsn.algolia.net/1/indexes/Question_development/browse?page=%7B%3Aquery%3D%3E%22test%22%7D&hitsPerPage=1000: {"message":"Invalid value for page parameter","status":400}

 (400)>
}
```

and another:

```
[7] pry(main)> index.browse { |hit| puts hit.class }; 'done'
"done"
[8] pry(main)> index.browse.each { |hit| puts hit.class }; 'done'
Array
Array
Array
Array
Array
Array
Array
Array
Array
"done"
```

You/your docs understanding of what is or is not an enumerator here is totally wrong

**Comment by redox** [comment]
Can you confirm the version of the API client you're using? It looks like you're using an old version of the `browse` implementation that was used to take a `page` number as argument instead of the `Hash` you see in the examples.

Regarding the enumerator, I would love to have your insights about why its implementation is wrong. The full code is [here](https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/index.rb#L144-L197). Keep in mind that to avoid breaking the API, the method accepts both a `page` (old browse) or a `Hash` (new browse).

**Comment by vincentwoo** [comment]
```
    algoliasearch (1.8.1)
      httpclient (~> 2.7.1)
      json (>= 1.5.1)
    algoliasearch-rails (1.14.1)
      algoliasearch (>= 1.2.14)
      json (>= 1.5.1)
```

problem is definitely on your end. have you even tried those code snippets?

you should probably return a real enumerator instead of asking people to pass a weird block to `browse`, very unrubylike. the parameters to the browse method itself are irrelevant

**Comment by redox** [comment]
> problem is definitely on your end. have you even tried those code snippets?

The `|hit|` block param is missing from the documentation snippet, I'll add it back.

> you should probably return a real enumerator instead of asking people to pass a weird block to browse, very unrubylike. the parameters to the browse method itself are irrelevant

OK, I just found the issue. You're initializing the `index` variable from the Rails integration, is that correct? It turns out that the bug is there. It's not a `Index` object but a wrapper used for the Rails integration internal (https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L225-L227), and this wrapper doesn't forward the `block` to the underlying `Index` object.

So instead of doing `index = MyModel.index` do `index = Algolia::Index.new(MyModel.index.name)` and it will quick fix the issue. In the meantime, I'll ensure the wrapper used in the Rails integration is forwarding the `block` to the `browse` method.

**Comment by vincentwoo** [comment]
amazing

**Comment by vincentwoo** [comment]
I would also like to state the opinion that I think it's pretty crazy to introduce a wrapping object with potential for complicated failure (as you see here) just to add an exception catching layer.

**Comment by robertjwhitney** [comment]
I would also like to point out that `browse`, when not passed a block, won't take a query param, it still uses the deprecated method. https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/index.rb#L195

**Comment by robertjwhitney** [comment]
Actually, if you do pass it a hash, it just passes that to page.

**Comment by redox** [comment]
Has been improved with https://github.com/algolia/algoliasearch-rails/pull/111
